feat: use same parameter for system_error_monitor
tier4/AutowareArchitectureProposal_launcher pull request #252
Opened 2022-03-28 10:37 UTC by h-ohta

## PR Type

- Improvement

## Related Links

## Description

- Use same parameter as real vehicle when psim is launched
- output dummy diag when psim is launched to avoid single point fault.

## Review Procedure

- When launching psim, no single point fault is occured, viewing `/system/emergency/hazard_status`
- When launching real vehicle, dummy diag publisher is not launched.

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2022-04-11 06:58 UTC, 0x126 commented
I checked it worked well.
![image](https://user-images.githubusercontent.com/8327162/162679479-e5bccbb0-2fbc-4609-982d-ddc38f471c94.png)

2022-04-11 07:22 UTC, kenji-miyake commented on system_launch/launch/system.launch.xml
> +        <arg name="diag_config_path_array" value="
Is it possible to replace this with `set_parameter`?

2022-04-11 07:28 UTC, kenji-miyake commented on system_launch/launch/system.launch.xml
> +        <arg name="diag_config_path_array" value="
I guess you can use this from Humble.
https://github.com/ros2/launch_ros/blob/d3970e5aa46b1449228f2d01d6b9e05555637d82/launch_ros/launch_ros/actions/set_parameters_from_file.py#L27-L28

2022-04-11 07:28 UTC, kenji-miyake commented on system_launch/launch/system.launch.xml
> +        <arg name="diag_config_path_array" value="
This also would be helpful.
https://github.com/autowarefoundation/autoware.universe/blob/main/common/global_parameter_loader/launch/global_params.launch.py

2022-04-11 07:50 UTC, kenji-miyake requested changes
Could you write some descriptions about the comparison between other approaches? :pray: 
We should provide rationals to AWF later.

2022-04-11 08:39 UTC, kenji-miyake commented on system_launch/launch/system.launch.xml
> +        <arg name="diag_config_path_array" value="
It seems we should discuss more basic things first, so I'll resolve this now.

2022-04-11 08:47 UTC, kenji-miyake commented
> 残りstaleするものについては33個あり、手作業ですべてのdiagについてxmlで記載するのは困難と判断

@h-ohta dummy_diag_publisherって1つ1行で書けませんでしたっけ？
困難と判断する理由が少し弱いと思うので、補足していただけないでしょうか？ :bow:

2022-04-11 08:49 UTC, h-ohta commented
最低でもdiag名を指定しないといけないので
```
  <include file="$(find-pkg-share dummy_diag_publisher)/launch/dummy_diag_publisher_node.launch.xml">
    <arg name="diag_name" value="velodyne_connection"/>
  </include>
```
のように3行かかります

2022-04-11 08:50 UTC, h-ohta commented
また、33は現在のstaleしているdiagの数なので、今後も増える可能性もあるし、33個を管理するのは容易ではないと思います

2022-04-11 08:52 UTC, kenji-miyake commented
すみません、「差分が1行」でした :bow: 
xmlでそのまま書く場合はおっしゃる通り3行ですね。

> 
また、33は現在のstaleしているdiagの数なので、今後も増える可能性もあるし、その都度管理するのは容易ではないと思います

容易ではない理由がイマイチ分からないので、もう少し補足をお願いしたいです。例えばどれくらいの頻度で変化しますか？

また、diag_config_path_arrayの方式だと管理ができる理由も分かっていません。
例外ケースが出てdummy.param.yamlで管理をしなければいけなくなっていると思うので、そこのコストは同じではないでしょうか？

2022-04-11 08:59 UTC, kenji-miyake commented on system_launch/config/diagnostic_aggregator/dummy.param.yaml
> +        contains: [": localization_accuracy"]
「これはdiagnostic_aggregator用の設定ではなくて、単にcontainsを取りたいんだけど、diagnostic_aggregatorの設定と同じ仕組みで取りたいから無理やり形式を合わせている」ということですかね。
ここは正直とっつきづらく、ハック的だと感じます :pleading_face:

2022-04-11 09:01 UTC, h-ohta commented
> 容易ではない理由がイマイチ分からないので、もう少し補足をお願いしたいです。例えばどれくらいの頻度で変化しますか？

launch.xmlに対する記述量が多くなってしまうので、今何があって何が足りないのかがわかりにくくなると考えられます。
例えばsystemやvehicleなどに分けてlaunch.xmlを分けるとまだいいかもしれないですが、system.launch.xmlへの記述がその分増えてしまいますね。
また、確かにすでにpilot-autoにあるdiagの変更頻度は少ないかも知れませんが、各プロダクトで必要なdiagは都度追加されるので、その考慮も必要かと思います。

> また、diag_config_path_arrayの方式だと管理ができる理由も分かっていません。
例外ケースが出てdummy.param.yamlで管理をしなければいけなくなっていると思うので、そこのコストは同じではないでしょうか？

確かにその懸念はおっしゃるとおりだと思います。
少しハック的にもなってしまっているのは否めないです

2022-04-11 09:06 UTC, kenji-miyake commented
> 例えばsystemやvehicleなどに分けてlaunch.xmlを分けるとまだいいかもしれないですが、system.launch.xmlへの記述がその分増えてしまいますね。

うーん、僕はこれで良いんじゃないかと思いますね〜
無理に自動化/共通化をするよりは、目視で「これは確かにSimulatorだと出ないね」と確認していける方が重要だと思います。
今はたまたま、sensor/system/vehicleが全てそうなっているようですが、今後そこにどういうダイアグが追加されるか分からないので、シンプルで柔軟な構成にしておく方が無難だと思いました。

2022-04-11 09:18 UTC, h-ohta commented
一旦それでやってみて作業量確認します

2022-04-11 09:45 UTC, h-ohta commented
@kenji-miyake 各種launch.xmlを作成しました
sensingは各sensor_kitで別途対応が必要になります

2022-04-11 09:50 UTC, kenji-miyake commented
一旦僕はこれで良さそうに見えます！
後はsensor_kitやsystem_monitor側で、`dummy_sensor_diag.launch.xml`や`dummy_cpu_monitor.launch.xml`的なものを用意すると、メンテナンス性が高くできるのではないでしょうか？

2022-04-11 09:52 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/system.launch.xml
> +    <arg name="diag_name" value="Tasks Summary"/>
Summaryって監視してましたっけ？何かのレポートだけだった気もします。
@ito-san 分かりますでしょうか？

2022-04-11 09:52 UTC, h-ohta commented
> 後は必要に応じて、sensor_kitやsystem_monitor側で、dummy_sensor_diag.launch.xmlやdummy_cpu_monitor.launch.xml的なものを用意すると、メンテナンス性が高くできるのではないでしょうか？

sensor_kitは必須として、system_monitor側で持ってもらえるとそれはそれでありがたいですね

2022-04-11 09:57 UTC, ito-san commented on system_launch/launch/dummy_diag_publisher/system.launch.xml
> +    <arg name="diag_name" value="Tasks Summary"/>
@kenji-miyake 監視していません、ただのレポートだけです。

2022-04-11 09:57 UTC, h-ohta commented
このPR作成をマージするためにsensor_kitも修正要ですが、aip_launcherを修正すればいいですか？

2022-04-11 09:58 UTC, h-ohta commented on system_launch/launch/dummy_diag_publisher/system.launch.xml
> +    <arg name="diag_name" value="Tasks Summary"/>
diagnostics_aggregatorの設定には存在するため、staleが出てるので追加してます

2022-04-11 09:59 UTC, kenji-miyake commented
> 
このPR作成をマージするためにsensor_kitも修正要ですが、aip_launcherを修正すればいいですか？

はい、それで良いと思います。dummy_diag_publisherを起動するlaunchを1つ追加する感じですよね？

2022-04-11 10:02 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/system.launch.xml
> +    <arg name="diag_name" value="Tasks Summary"/>
確かにありますね。（昔僕が間違えて足してしまったのかも…すみません）
こちらを消す前提でこのlaunchからも消してしまって良いような気はしますが、出していても悪影響はないと思うのでどうするかはお任せします。

https://github.com/autowarefoundation/autoware.universe/blob/6dbbaeeeac30dd67fe2fdc61cf18ba2919faa9e0/system/system_error_monitor/config/diagnostic_aggregator/system.param.yaml#L169-L173

2022-04-11 10:03 UTC, h-ohta commented on system_launch/launch/dummy_diag_publisher/system.launch.xml
> +    <arg name="diag_name" value="Tasks Summary"/>
こちらから消してもrqt_robot_monitorでは見えてしまうので、dummyで対応するほうがいいと思います

2022-04-11 11:24 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
@h-ohta 毎回3行書くのも大変かなと思ったので、こんな感じで書けるように試してみたらできましたが、取り入れますか？

```
  <include file="$(find-pkg-share dummy_diag_publisher)/launch/launch_multiple.launch.py">
    <arg name="diag_names" value="[
      velodyne_connection,
      velodyne_temperature,
      livox_ptp_signal,
      camera_connection,
      lane_departure,
      obstacle_crash,
      vehicle_errors,
      can_bus_connection,
      speaker,
    ]"/>
  </include>
```

https://github.com/autowarefoundation/autoware.universe/blob/6dbbaeeeac30dd67fe2fdc61cf18ba2919faa9e0/system/dummy_diag_publisher/launch/dummy_diag_publisher.launch.xml#L25-L66 と同等です。コメントは書けなさそうです :pleading_face:

2022-04-11 11:27 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
launch.pyを見てみないとなんとも言えないかもしれないので載せておきます。

```python
def launch_setup(context, *args, **kwargs):
    param_dict = normalize_parameter_dict({"diag_names": LaunchConfiguration("diag_names")})
    diag_names = evaluate_parameter_dict(context, param_dict)["diag_names"]

    return [
        IncludeLaunchDescription(
            FrontendLaunchDescriptionSource(
                [
                    FindPackageShare("dummy_diag_publisher"),
                    "/launch/dummy_diag_publisher_node.launch.xml",
                ]
            ),
            launch_arguments={
                "diag_name": diag_name,
            }.items(),
        )
        for diag_name in diag_names
    ]


def generate_launch_description():
    return LaunchDescription(
        [
            DeclareLaunchArgument("diag_names"),
            OpaqueFunction(function=launch_setup),
        ]
    )
```

2022-04-11 16:45 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
あと、色々と考えてみましたが、元の実装はsystem_launchでやるのではなく、dummy_diag_publisherの中に「diagnostic_aggregatorのconfigをInputとして起動するlaunch」を追加し、それを呼ぶ形式ならAcceptableになる気がします。

2022-04-12 01:20 UTC, h-ohta commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
> （あと、uuidは本当に必要か等は検討したいですけど）

ComposableNodeを作成する際にAnonNameでノード名指定する場合、複数のComposableNodeがすべて同じ名前になってしまうのでやむなくuuidを使ったという経緯があります。

2022-04-12 01:23 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
なるほど。であればそれはコメントで書いておくと良かったかな？と思います。

2022-04-12 01:25 UTC, h-ohta commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
ご提案いただいたlaunch.pyの手法はとてもいいと思いますが、おっしゃるとおりdummy_diag_publisher側で持つものなので、今回のPRとしては現在あるもので一旦クローズとしたいです
今後まとめたいなら実施する、ということでいいかなと

2022-04-12 01:27 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
OKです。

> 「diagnostic_aggregatorのconfigをInputとして起動するlaunch」を追加し、それを呼ぶ形式ならAcceptableになる気がします。

これはどうしますか？説明が分かりづらかったですかね？

2022-04-12 01:29 UTC, h-ohta commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
> 「diagnostic_aggregatorのconfigをInputとして起動するlaunch」を追加し、それを呼ぶ形式ならAcceptableになる気がします。

いや意味はわかったのですが、結局ハック的なやり方になる未来がちょっと見えてしまったので悩ましいです

2022-04-12 01:31 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
> 結局ハック的なやり方になる未来がちょっと見えてしまったので

例えばどういうことでしょうか？（もしイメージあれば）

2022-04-12 01:32 UTC, h-ohta commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
今回と同じ実装をそのまま置くのであれば、containsだけを書いたparamを使われてしまったりとかすでに指摘されてるお話が考えられるかなと思いました。

2022-04-12 01:35 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
そこはルール決めとレビューで防げる問題だとは思います。
どうしても気がかりであれば、一旦これでマージするのは良いと思います。

2022-04-12 01:37 UTC, h-ohta commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
一旦これでマージでいいと思います

2022-04-12 02:03 UTC, kenji-miyake commented on system_launch/launch/dummy_diag_publisher/control.launch.xml
> +
了解です。では他プロダクトのメンテナのコメントを待ちますか！

2022-04-18 02:10 UTC, 0x126 approved these changes
LGTM

2022-04-18 02:16 UTC, tkimura4 approved these changes

2022-04-19 02:16 UTC, h-ohta commented
@yn-mrse こちらもお願いできますか・・・？

2022-04-19 03:32 UTC, yn-mrse approved these changes
LGTM！

2022-04-19 03:36 UTC, h-ohta commented
@kenji-miyake 各プロダクトのapproveをいただいたので、他に問題がなければマージとしたいです

2022-04-19 03:39 UTC, kenji-miyake approved these changes
ありがとうございます！

2022-04-19 03:39 UTC, merged

2022-07-11 03:31 UTC, shmpwk commented
@h-ohta こちらdiag_nameにspaceが入っていて大丈夫でした？
xx1ではありましたが，spaceをいれてはいけないとエラーがでたので．
```
$ ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/Downloads/sample-map-planning vehicle_model:=jpntaxi sensor_model:=aip_xx1
[INFO] [launch]: All log files can be found below /home/shumpeiwakabayashi/.ros/log/2022-07-11-11-53-11-425646-dpc1908003-122595
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch_ros.actions.node]: Error while expanding or validating node name or namespace for 'package=[<launch.substitutions.text_substitution.TextSubstitution object at 0x7fe2d0454d00>], executable=[<launch.substitutions.text_substitution.TextSubstitution object at 0x7fe2d0454160>], name=[<launch.substitutions.launch_configuration.LaunchConfiguration object at 0x7fe2d0454490>], namespace=None':
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidNodeNameException("Invalid node name: node name must not contain characters other than alphanumerics or '_':\n  'NTP Offset'\n      ^")>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 11 more times]
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch_ros/actions/node.py", line 465, in execute
    self._perform_substitutions(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch_ros/actions/node.py", line 379, in _perform_substitutions
    validate_node_name(self.__expanded_node_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/validate_node_name.py", line 34, in validate_node_name
    raise InvalidNodeNameException(node_name, error_msg, invalid_index)
rclpy.exceptions.InvalidNodeNameException: Invalid node name: node name must not contain characters other than alphanumerics or '_':
  'NTP Offset'
      ^
```